[package]
name = "rust-demo"
version = "0.1.0"
authors = ["geenva <geenva@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
colour = "0.6.0"